# Generated by Django 2.0.10 on 2019-01-16 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20190113_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 16), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time(15, 30, 35, 35446), null=True, verbose_name='Time'),
        ),
    ]
