# Generated by Django 2.0.10 on 2019-01-17 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20190116_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 17), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time(16, 38, 39, 145600), null=True, verbose_name='Time'),
        ),
    ]
